project:
  type: website
  output-dir: docs
  post-render:
    - cmd.exe /c copy CNAME docs\\CNAME
  pre-render: generate_redirects.py

website:
  title: "TidyT.manishdatt.com"
  search: false
  navbar:
    right:
      - icon: house-door
        href: https://manishdatt.com/
      - icon: linkedin
        href: https://in.linkedin.com/in/manishdatt
      - icon: bi-twitter-x
        href: https://twitter.com/dr_manishdatt
#      - icon: bi-bluesky
#      - href: https://bsky.app/profile/manishdatt.com
#  page-footer:
#      href: "footer.html"
resources:
    - r
format:
  html:
    theme: sandstone
    include-after-body: _giscus.html
#    css: styles.css
#    include-after-body: footer.html
comments:
  giscus: 
    repo: "manishdatt/TidyTuesday"
    category: General           # Must match the category name in GitHub Discussions
    mapping: pathname           # Ensures each page creates its own thread
    theme: light                # or dark / preferred_color_scheme
    loading: lazy               # optional: improves load performance
execute:
    warning: false
    eval: true